const profileData = [
    {
        id:1,
        profileName:"Codeforces",
        demo:"https://codeforces.com/profile/sahilanand",
        imgsrc:"/cf.png"
    },
    {
        id:2,
        profileName:"Leetcode",
        demo:"https://leetcode.com/sahilanand/",
        imgsrc:"/lc.svg"
    },
    {
        id:3,
        profileName:"Codechef",
        demo:"https://www.codechef.com/users/sahilanand30",
        imgsrc:"/cc.jpg"
    },
    {
        id:4,
        profileName:"Hackerrank",
        demo:"https://www.hackerrank.com/sahilhanand",
        imgsrc:"/hr.jpg"
    },
    {
        id:5,
        profileName:"CSES",
        demo:"https://cses.fi/user/83389",
        imgsrc:"/cses.png"
    },
    {
        id:6,
        profileName:"Github",
        demo:"https://github.com/sahilanand30",
        imgsrc:"/gh.png"
    },
]

export default profileData;